defaults:
  - parameters: pretraining
  - _self_

entity: "jvpoulos"
project: "diabetes_pred_temporal"
program: pretrain.py
method: bayes
name: EST_sweep
metric:
  goal: minimize
  name: tuning_loss
early_terminate:
  type: hyperband
  min_iter: 1000
